import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
const source = readFileSync("public/brand/zaithe-nav-white.svg", "utf8");
const paths = [...source.matchAll(/<path d="([^"]+)"/g)].map((m) => m[1]);
const edges: {
  from: number[];
  to: number[];
  degrees: number;
  length: number;
}[] = [];
for (const path of paths) {
  const tokens = path.match(/[MLHVCZ]|-?\d+(?:\.\d+)?/g)!;
  let x = 0,
    y = 0;
  for (let i = 0; i < tokens.length;) {
    const command = tokens[i++];
    const count = (
      { M: 2, L: 2, H: 1, V: 1, C: 6, Z: 0 } as Record<string, number>
    )[command];
    if (count === undefined)
      throw new Error(`Unsupported SVG command ${command}`);
    const values = tokens.slice(i, i + count).map(Number);
    i += count;
    if (command === "Z") continue;
    const nx =
      command === "V" ? x : command === "H" ? values[0] : values[count - 2];
    const ny = command === "H" ? y : values[count - 1];
    const dx = nx - x,
      dy = ny - y,
      length = Math.hypot(dx, dy);
    if (command === "L" && length > 400 && dx !== 0 && dy !== 0) {
      let degrees = (Math.atan2(dy, dx) * 180) / Math.PI;
      if (degrees < 0) degrees += 180;
      edges.push({ from: [x, y], to: [nx, ny], degrees, length });
    }
    x = nx;
    y = ny;
  }
}
if (edges.length !== 4)
  throw new Error("Expected the four long diagonal edges in the approved mark");
// Length-weighted axial circular mean: both directions describe the same axis.
const angle =
  (Math.atan2(
    edges.reduce(
      (sum, e) => sum + e.length * Math.sin((e.degrees * Math.PI) / 90),
      0,
    ),
    edges.reduce(
      (sum, e) => sum + e.length * Math.cos((e.degrees * Math.PI) / 90),
      0,
    ),
  ) *
    90) /
  Math.PI;
const data = {
  angleDegrees: angle,
  sourceSha256: createHash("sha256").update(source).digest("hex"),
  rangeDegrees: [
    Math.min(...edges.map((e) => e.degrees)),
    Math.max(...edges.map((e) => e.degrees)),
  ],
  edges,
};
const output =
  "// Generated by scripts/measure-passage.ts from the approved SVG. Do not hand edit.\nexport const passage = " +
  JSON.stringify(data, null, 2) +
  " as const;\n";
if (process.argv.includes("--check")) {
  if (readFileSync("src/lib/passage.ts", "utf8") !== output)
    throw new Error("Passage geometry is stale");
} else writeFileSync("src/lib/passage.ts", output);
console.log(
  JSON.stringify({
    angleDegrees: angle,
    rangeDegrees: data.rangeDegrees,
    edges: edges.length,
  }),
);
