// Generated by scripts/measure-passage.ts from the approved SVG. Do not hand edit.
export const passage = {
  "angleDegrees": 39.821659983867036,
  "sourceSha256": "a95ce38aa888f1a98eab6265df44951444f9d5257469f1c39d1c96f3e0d829c0",
  "rangeDegrees": [
    39.749055249958104,
    39.90188955498894
  ],
  "edges": [
    {
      "from": [
        1090,
        1082
      ],
      "to": [
        695,
        752
      ],
      "degrees": 39.87683446287184,
      "length": 514.7086554547145
    },
    {
      "from": [
        642,
        600
      ],
      "to": [
        143,
        185
      ],
      "degrees": 39.749055249958104,
      "length": 649.019260114829
    },
    {
      "from": [
        108,
        225
      ],
      "to": [
        517,
        567
      ],
      "degrees": 39.90188955498894,
      "length": 533.1463213790375
    },
    {
      "from": [
        581,
        741
      ],
      "to": [
        1029,
        1114
      ],
      "degrees": 39.780402730381674,
      "length": 582.9519705773366
    }
  ]
} as const;
